[project]
name = "dash"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "comm>=0.2.3",
    "flask>=3.1.3",
    "importlib-metadata>=9.0.0",
    "janus>=2.0.0",
    "nest-asyncio>=1.6.0",
    "plotly>=6.9.0",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "retrying>=1.4.2",
    "setuptools>=84.0.0",
    "typing-extensions>=4.16.0",
    "werkzeug>=3.1.8",
]
